version: "3.7"

services:
  app:
    container_name: backend
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    command: ./docker/django/start.sh
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - celery

  rabbit:
    container_name: rabbit
    image: rabbitmq:3.7.8
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5432"

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    command: celery -A app worker -l info
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - rabbit

  db:
    container_name: db
    image: postgres:10.1-alpine
    restart: on-failure
    env_file:
      - .env
    volumes:
      - pgdata:${PGDATA:-/var/lib/postgresql/data}
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-example@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-changemypassword}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"

volumes:
    pgdata:
    pgadmin:
